platform :ios, '14.0'
use_frameworks!

# Workspace: iosApp.xcworkspace

target 'iosApp' do
  # Consome frameworks gerados pelos módulos KMP via cocoapods
  pod 'Core', :path => '../core'
  pod 'AppMan', :path => '../app'

  # Link explícito dos pods Firebase necessários para Storage
  pod 'FirebaseCore'
  pod 'FirebaseStorage'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Garante que todos os pods sejam buildados corretamente para arm64
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      # Força linkage dinâmica para evitar símbolos indefinidos
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end

