package com.walcker.flickly.products.audio.strings

internal data class HomeAudioStrings(
    val titleToolbar: String = "",
    val chapter: (String) -> String = { "" },
    val peace: String = "",
    val books: String = "",
    val language: String = "",
    val oldTestament: String = "",
    val newTestament: String = "",
    val oldTestamentAll: String = "",
    val newTestamentAll: String = "",
    val allBooks: String = "",
    val ptName: String = "",
    val enName: String = "",
    val urName: String = "",
    val paInName: String = "",
    val paPkName: String = "",
    val sdPkName: String = "",
    val sdInName: String = "",
    val chaptersCount: (Int) -> String = { "" },
)

internal val homeAudioStringsPt = HomeAudioStrings(
    titleToolbar = "Bíblia em Áudio",
    chapter = { "Capítulo $it" },
    peace = "Paz seja convosco",
    books = "Livros",
    language = "Idioma",
    oldTestament = "AT",
    newTestament = "NT",
    oldTestamentAll= "Antigo Testamento",
    newTestamentAll = "Novo Testamento",
    allBooks = "Todos os Livros",
    ptName = "Português",
    enName = "English",
    urName = "Urdu",
    paInName = "Punjabi (IN)",
    paPkName = "Punjabi (PK)",
    sdPkName = "Sindi (PK)",
    sdInName = "Sindi (IN)",
    chaptersCount = { "$it capítulos" },
)

internal val homeAudioStringsEn = HomeAudioStrings(
    titleToolbar = "Audio Bible",
    chapter = { "Chapter $it" },
    peace = "Peace be with you",
    books = "Books",
    language = "Language",
    oldTestament = "OT",
    newTestament = "NT",
    oldTestamentAll = "Old Testament",
    newTestamentAll = "New Testament",
    allBooks = "All Books",
    ptName = "Português",
    enName = "English",
    urName = "Urdu",
    paInName = "Punjabi - IN",
    paPkName = "Punjabi - PK",
    sdPkName = "Sindi (PK)",
    sdInName = "Sindi (IN)",
    chaptersCount = { "$it chapters" },
)

internal val homeAudioStringsUr = HomeAudioStrings(
    titleToolbar = "آڈیو بائبل",
    chapter = { "باب $it" },
    peace = "آپ پر سلامتی ہو",
    books = "کتابیں",
    language = "زبان",
    oldTestament = "عہدِ عتیق",
    newTestament = "عہدِ جدید",
    oldTestamentAll = "عہدِ عتیق",
    newTestamentAll = "عہدِ جدید",
    allBooks = "تمام کتابیں",
    ptName = "پرتگالی",
    enName = "انگریزی",
    urName = "اردو",
    paInName = "پنجابی (بھارت)",
    paPkName = "پنجابی (پاکستان)",
    sdPkName = "سندھی (پاکستان)",
    sdInName = "سندھی (بھارت)",
    chaptersCount = { "$it ابواب" },
)

internal val homeAudioStringsPaIn = HomeAudioStrings(
    titleToolbar = "ਆਡੀਓ ਬਾਈਬਲ",
    chapter = { "ਅਧਿਆਇ $it" },
    peace = "ਤੁਹਾਡੇ ਉੱਤੇ ਸ਼ਾਂਤੀ ਹੋਵੇ",
    books = "ਕਿਤਾਬਾਂ",
    language = "ਭਾਸ਼ਾ",
    oldTestament = "ਪੁਰਾਣਾ ਨਿਯਮ",
    newTestament = "ਨਵਾਂ ਨਿਯਮ",
    oldTestamentAll = "ਪੁਰਾਣਾ ਨਿਯਮ",
    newTestamentAll = "ਨਵਾਂ ਨਿਯਮ",
    allBooks = "ਸਾਰੀਆਂ ਕਿਤਾਬਾਂ",
    ptName = "ਪੁਰਤਗਾਲੀ",
    enName = "ਅੰਗਰੇਜ਼ੀ",
    urName = "ਉਰਦੂ",
    paInName = "ਪੰਜਾਬੀ (ਭਾਰਤ)",
    paPkName = "ਪੰਜਾਬੀ (ਪਾਕਿਸਤਾਨ)",
    sdPkName = "ਸਿੰਧੀ (ਪਾਕਿਸਤਾਨ)",
    sdInName = "ਸਿੰਧੀ (ਭਾਰਤ)",
    chaptersCount = { "$it ਅਧਿਆਇ" },
)

internal val homeAudioStringsPaPK = HomeAudioStrings(
    titleToolbar = "آڈیو بائبل",
    chapter = { "باب $it" },
    peace = "تہاڈے اُتے سلامتی ہووے",
    books = "کتاباں",
    language = "زبان",
    oldTestament = "پرانا عہدنامہ",
    newTestament = "نواں عہدنامہ",
    oldTestamentAll = "پرانا عہدنامہ",
    newTestamentAll = "نواں عہدنامہ",
    allBooks = "ساریاں کتاباں",
    ptName = "پرتگالی",
    enName = "انگریزی",
    urName = "اردو",
    paInName = "پنجابی (بھارت)",
    paPkName = "پنجابی (پاکستان)",
    sdPkName = "سندھی (پاکستان)",
    sdInName = "سندھی (بھارت)",
    chaptersCount = { "$it باب" },
)

internal val homeAudioStringsSdPk = HomeAudioStrings(
    titleToolbar = "آڊيو بائبل",
    chapter = { "باب $it" },
    peace = "توهان تي سلامتي هجي",
    books = "ڪتابون",
    language = "ٻولي",
    oldTestament = "پراڻو عهد نامو",
    newTestament = "نئون عهد نامو",
    oldTestamentAll = "پراڻو عهد نامو",
    newTestamentAll = "نئون عهد نامو",
    allBooks = "سڀ ڪتاب",
    ptName = "پرتگالي",
    enName = "انگريزي",
    urName = "اردو",
    paInName = "پنجابي (ڀارت)",
    paPkName = "پنجابي (پاڪستان)",
    sdPkName = "سنڌي (پاڪستان)",
    sdInName = "سنڌي (ڀارت)",
    chaptersCount = { "$it باب" },
)

internal val homeAudioStringsSdIn = HomeAudioStrings(
    titleToolbar = "ऑडियो बाइबल",
    chapter = { "अध्याय $it" },
    peace = "तुम्हां ते शांति हुजे",
    books = "पुस्तकें",
    language = "भाषा",
    oldTestament = "पुरानो नियम",
    newTestament = "नवो नियम",
    oldTestamentAll = "पुरानो नियम",
    newTestamentAll = "नवो नियम",
    allBooks = "सब पुस्तकें",
    ptName = "पुर्तगाली",
    enName = "अंग्रेज़ी",
    urName = "उर्दू",
    paInName = "पंजाबी (भारत)",
    paPkName = "पंजाबी (पाकिस्तान)",
    sdPkName = "सिंधी (पाकिस्तान)",
    sdInName = "सिंधी (भारत)",
    chaptersCount = { "$it अध्याय" },
)