package com.walcker.flickly.products.audio.features.domain.model

import com.walcker.flickly.products.audio.strings.BibleBooksStrings

internal enum class AudioBook(
    val folderName: (BibleBooksStrings) -> String,
    val totalChapters: Int
) {
    Genesis(folderName = { it.genesis }, totalChapters = 50),
    Exodus(folderName = { it.exodus }, totalChapters = 40),
    Leviticus(folderName = { it.leviticus }, totalChapters = 27),
    Numbers(folderName = { it.numbers }, totalChapters = 36),
    Deuteronomy(folderName = { it.deuteronomy }, totalChapters = 34),
    Joshua(folderName = { it.joshua }, totalChapters = 24),
    Judges(folderName = { it.judges }, totalChapters = 21),
    Ruth(folderName = { it.ruth }, totalChapters = 4),
    FirstSamuel(folderName = { it.firstSamuel }, totalChapters = 31),
    SecondSamuel(folderName = { it.secondSamuel }, totalChapters = 24),
    FirstKings(folderName = { it.firstKings }, totalChapters = 22),
    SecondKings(folderName = { it.secondKings }, totalChapters = 25),
    FirstChronicles(folderName = { it.firstChronicles }, totalChapters = 29),
    SecondChronicles(folderName = { it.secondChronicles }, totalChapters = 36),
    Ezra(folderName = { it.ezra }, totalChapters = 10),
    Nehemiah(folderName = { it.nehemiah }, totalChapters = 13),
    Esther(folderName = { it.esther }, totalChapters = 10),
    Job(folderName = { it.job }, totalChapters = 42),
    Psalms(folderName = { it.psalms }, totalChapters = 150),
    Proverbs(folderName = { it.proverbs }, totalChapters = 31),
    Ecclesiastes(folderName = { it.ecclesiastes }, totalChapters = 12),
    SongOfSolomon(folderName = { it.songOfSolomon }, totalChapters = 8),
    Isaiah(folderName = { it.isaiah }, totalChapters = 66),
    Jeremiah(folderName = { it.jeremiah }, totalChapters = 52),
    Lamentations(folderName = { it.lamentations }, totalChapters = 5),
    Ezekiel(folderName = { it.ezekiel }, totalChapters = 48),
    Daniel(folderName = { it.daniel }, totalChapters = 12),
    Hosea(folderName = { it.hosea }, totalChapters = 14),
    Joel(folderName = { it.joel }, totalChapters = 3),
    Amos(folderName = { it.amos }, totalChapters = 9),
    Obadiah(folderName = { it.obadiah }, totalChapters = 1),
    Jonah(folderName = { it.jonah }, totalChapters = 4),
    Micah(folderName = { it.micah }, totalChapters = 7),
    Nahum(folderName = { it.nahum }, totalChapters = 3),
    Habakkuk(folderName = { it.habakkuk }, totalChapters = 3),
    Zephaniah(folderName = { it.zephaniah }, totalChapters = 3),
    Haggai(folderName = { it.haggai }, totalChapters = 2),
    Zechariah(folderName = { it.zechariah }, totalChapters = 14),
    Malachi(folderName = { it.malachi }, totalChapters = 4),
    Matthew(folderName = { it.matthew }, totalChapters = 28),
    Mark(folderName = { it.mark }, totalChapters = 16),
    Luke(folderName = { it.luke }, totalChapters = 24),
    John(folderName = { it.john }, totalChapters = 21),
    Acts(folderName = { it.acts }, totalChapters = 28),
    Romans(folderName = { it.romans }, totalChapters = 16),
    FirstCorinthians(folderName = { it.firstCorinthians }, totalChapters = 16),
    SecondCorinthians(folderName = { it.secondCorinthians }, totalChapters = 13),
    Galatians(folderName = { it.galatians }, totalChapters = 6),
    Ephesians(folderName = { it.ephesians }, totalChapters = 6),
    Philippians(folderName = { it.philippians }, totalChapters = 4),
    Colossians(folderName = { it.colossians }, totalChapters = 4),
    FirstThessalonians(folderName = { it.firstThessalonians }, totalChapters = 5),
    SecondThessalonians(folderName = { it.secondThessalonians }, totalChapters = 3),
    FirstTimothy(folderName = { it.firstTimothy }, totalChapters = 6),
    SecondTimothy(folderName = { it.secondTimothy }, totalChapters = 4),
    Titus(folderName = { it.titus }, totalChapters = 3),
    Philemon(folderName = { it.philemon }, totalChapters = 1),
    Hebrews(folderName = { it.hebrews }, totalChapters = 13),
    James(folderName = { it.james }, totalChapters = 5),
    FirstPeter(folderName = { it.firstPeter }, totalChapters = 5),
    SecondPeter(folderName = { it.secondPeter }, totalChapters = 3),
    FirstJohn(folderName = { it.firstJohn }, totalChapters = 5),
    SecondJohn(folderName = { it.secondJohn }, totalChapters = 1),
    ThirdJohn(folderName = { it.thirdJohn }, totalChapters = 1),
    Jude(folderName = { it.jude }, totalChapters = 1),
    Revelation(folderName = { it.revelation }, totalChapters = 22),
}